server:
  port: 3344

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yk2911533608/springcloud-config.git
          search-paths: springcloud-config #搜索的仓库
          skip-ssl-validation: true    #跳过ssl验证
          username: 2911533608@qq.com
          password: github31415926
      label: main #读取分支
  rabbitmq:
    host: 192.168.2.68
    port: 5672
    username: root
    password: 123123

management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"