server:
  port: 9527


eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
  instance:
    hostname: cloud-gateway-service


spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #路由id,保证唯一就行
          uri: lb://CLOUD-PAYMENT-SERVICE # uri: http://localhost:8001 匹配后提供的路由地址
          predicates:
            - Path=/payment/get/** #路径相匹配的进行路由
        - id: payment_routh2
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            - Path=/payment/lb/**
            - After=2023-02-21T14:08:36.352+08:00[Asia/Shanghai] #在指定的时间后才生效
            - Cookie=username,yk #请求的cookie中必须要有username=yk的键值对
            - Header=X-Request-Id,\d+ #请求头中需要带有X-Request-Id,值要匹配正则表达式
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由