server:
  port: 7001

eureka:
  instance:
    hostname: eureka7001.com
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: false
    #false 表示自己端就是注册中心,我们的职责就是维护服务实力,并不需要去检索服务
    fetch-registry: false
    service-url:
      #设置与eureka server交互的地址,查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
